---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # renovate
  - https://github.com/jetstack/cert-manager/releases/download/v1.7.3/cert-manager.yaml
patches:
  - target:
      kind: Deployment
      name: cert-manager
    path: deployment.patch.yaml
resources:
  - clusterissuer.yaml
  - secret.enc.yaml
