---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
