---
- name: Set hostname
  become: yes
  command: raspi-config nonint do_hostname "{{ hostname }}"

- name: Mount USB drive
  ansible.posix.mount:
    path: /mnt/usb
    src: /dev/sda1
    fstype: ext4
    opts: defaults
    passno: "2"
    state: mounted

- name: Install open-iscsi
  ansible.builtin.package:
    name: open-iscsi
    state: present
