---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: pihole.homelab.adtennant.dev
      tls:
        - hosts:
            - pihole.homelab.adtennant.dev
          secretName: pihole-tls
    persistentVolumeClaim:
      enabled: true
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
    serviceDns:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
