---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
  - service.yaml
generators:
  - secret-generator.yaml
