---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: home-assistant
