---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: home-assistant
secretFrom:
  - metadata:
      name: home-assistant
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    type: Opaque
    files:
      - configuration.yaml=./configuration.enc.yaml
