---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      port: 8086
      protocol: TCP
      targetPort: influxdb
