---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/adtennant/homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  dependsOn:
    - name: base
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns
      namespace: external-dns
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: Deployment
      name: system-upgrade-controller
      namespace: system-upgrade
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik
  interval: 10m0s
  path: ./k8s/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: homelab
  namespace: flux-system
spec:
  dependsOn:
    - name: core
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./k8s/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  validation: client
