---
k3s_version: v1.25.4+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: >
  --disable local-storage
  --disable servicelb
  --disable traefik
  --node-taint "node-role.kubernetes.io/master=true:NoSchedule"
extra_agent_args:
