---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
bases:
  # renovate
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.47.0/bundle.yaml
  - namespace.yaml
