---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-internal
spec:
  interval: 5m
  releaseName: internal
  chart:
    spec:
      chart: external-dns
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    domainFilters:
      - homelab.local
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    extraArgs:
      - --pihole-server=http://pihole-web.pihole.svc.cluster.local
    # Temporary
    # https://github.com/kubernetes-sigs/external-dns/issues/3176
    image:
      repository: gcr.io/k8s-staging-external-dns/external-dns
      tag: v20221229-external-dns-helm-chart-1.12.0-22-g4008582c-arm64v8
    policy: sync
    provider: pihole
    registry: noop
