---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
spec:
  interval: 5m
  releaseName: internal
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    domainFilters:
      - homelab.local
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pihole-web.pihole.svc.cluster.local
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    extraArgs:
      - --pihole-api-version=6
    # Temporary
    # https://github.com/kubernetes-sigs/external-dns/issues/5362
    image:
      repository: gcr.io/k8s-staging-external-dns/external-dns
      tag: v20250510-v0.16.1-151-g2f165e87
    policy: sync
    provider: pihole
    registry: noop
