---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
bases:
  # renovate
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.2.6/deploy/longhorn.yaml
patchesStrategicMerge:
  - configmap.patch.yaml
resources:
  - ingress.yaml
