apiVersion: v1
kind: Secret
metadata:
    name: oidc
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:wyuFJu680to=,iv:ISZcIZ34/d8XXFlK2aFu6lgAQBqGvh7NIGMrwbMOSFE=,tag:mYdAnkFt4mU909IEVYiB8Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:vyZ6sB30zq2qU+TAvME3DVHLPDsiZ7L3qnt9hvFFyMZUrCcDAV8ccGwZxhFMzg28kmjs8XB7AKyIT67enAmo0Q==,iv:+stOsCXHHay1jiBStVT8oEVwsNpS0myF8FPFZdvwqMs=,tag:C2khFggJ3OGbzs1/96+7VQ==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:9KSYT3G/jilnsBEz1QJfurt01e/2Jql3IQ==,iv:IXwSGV/Goip1B0sQCYScGu4uXxkKYvfPWvdCQo6TYKI=,tag:Kheve6ICtIKlKrlqEAEz7w==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:IvAdN1Q=,iv:bNFMAouolGWRf6ljDUk/x4VYLaDiEj+RDSKDFdRaMvY=,tag:okXJM3cubZkCSnxWOcGq1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T19:02:46Z"
    mac: ENC[AES256_GCM,data:EOAPOq3WxgO0qT2GM6Bo8qvOnFYwFtyFEmBNVTzxS9mdLYO09JrXAN+VESrcaYeaXeWkqMNxMYMJIbkHl63pjK5YuOKhrkRnhZ8JV1zbq7C8o6jwYQpH3T+6nMy/zhjWrgYVq8harZwJgTJMOH3YCZQN3rD8l9X4BGwHGN+u+SU=,iv:9Lni31ldBrQys03NHpKfjFHQ1quWX9pSEfehwFNbanY=,tag:PreryRzMF3jAThN4gm9G9g==,type:str]
    pgp:
        - created_at: "2023-01-08T10:03:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Zy+lejmH90ARAAk/reL808X8aVAp7IRRaHVj3rvHIqT2s+QqnO3tVMfHNm
            UU5K3SgGOVuVqHH2sxvjSdu7VimMLSyhCiOCFToaq3+ztJ5rQ1ccCaWZJvyRe2wD
            6eLdnl6X1tvJNRjTTmXnsg+EtJTVRVRygWqlIV2iZX5rVJ0KMUGJ0fVWTF+HNmEM
            6B9IZJkgHf5wvjlxHFwA5THPk+PwChUd+NVexyoXHPjePYaZl/32ouH9DkaqYDMZ
            Rja8aPk8TIYh6e0p+nBJVSIXVUgVQORJ4uk1bpuk7B+AQK2defbRzTM4g2hcR8Ve
            84V63W0sF8EQTGOsVNfltS9SCWQKgC5t99diIW41906tslsgb+qmWiTQ6RHj5x/K
            gGH46j9c8yKapf7Lvv2eBKjsnpaqqqGTCpvozSgsh+mIxxNSXXA9SaGYY9kmj8Os
            2mVBv0sP2gZBqhLWHPWRc2oaiYuckPLl5BOU/VvfvRUp929sUsXiEHn624UO8csr
            rg3/xNCtwD4n54ifTjq2IhdmfWteiUsI5bsEm0hJWgEnw1JVWInTRMXy8oFwP6R+
            obc6ih0s6qINxSW4l20H1XeUIIZ8632YqeRqm56GjwUZFbn9eCbpTWphAgsIx2ms
            YGDiUn4HDq5cMzLB02eho6se9nSnNtq8z/Ym23MPCBGySReeRvDwGdqBl7fmnyrU
            aAEJAhCfsSnniOjxLtgTdSPyIJCPGXRI34xghnvKYWpQ0rNSDRBl+xQmZfU91Q7P
            T3j9lM6ZlumYO3PWk1Hqqt4Q7Hzvjva0YnO1lrfWaBZGgXATQ8ru3e30xHXyuil8
            QpI0vCuHprRo
            =Vmv+
            -----END PGP MESSAGE-----
          fp: 8858948C94A7459AB04B59D37BCE1C5040D2EEE4
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
