---
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --default-issuer-name=letsencrypt
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --default-issuer-kind=ClusterIssuer
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --default-issuer-group=cert-manager.io
