---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.70.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  values:
    DNS1: 1.1.1.1
    DNS2: 1.0.0.1
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.middlewares: pihole-redirect@kubernetescrd
      hosts:
        - pihole.homelab.local
    persistentVolumeClaim:
      enabled: true
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
        - 1.0.0.1
    serviceDns:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
