---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.33.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    additionalArguments:
      - --api.insecure=true
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      access:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        publishedService:
          enabled: true
