---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfingerd
  labels:
    app: gfingerd
spec:
  selector:
    matchLabels:
      app: gfingerd
  replicas: 2
  template:
    metadata:
      labels:
        app: gfingerd
    spec:
      containers:
        - name: gfinderg
          image: ghcr.io/adtennant/gfingerd:v0.3.0
          args:
            - --config
            - /etc/gfingerd/config/config.yaml
          ports:
            - name: finger
              containerPort: 79
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
          volumeMounts:
            - name: config
              mountPath: /etc/gfingerd/config
              readOnly: true
            - name: home
              mountPath: /home/nonroot
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gfingerd
            items:
              - key: config.yaml
                path: config.yaml
        - name: home
          nfs:
            server: magical-box.local
            path: /volume1/homelab
            readOnly: true
