---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfingerd
  labels:
    app: gfingerd
spec:
  selector:
    matchLabels:
      app: gfingerd
  replicas: 2
  template:
    metadata:
      labels:
        app: gfingerd
    spec:
      containers:
        - name: gfinderg
          image: ghcr.io/adtennant/gfingerd
          args:
            - --config
            - /etc/gfingerd/config/config.yaml
          ports:
            - name: finger
              containerPort: 79
          volumeMounts:
            - name: config
              mountPath: /etc/gfingerd/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gfingerd
            items:
              - key: config.yaml
                path: config.yaml
