---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gfingerd
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

configMapGenerator:
  - name: gfingerd
    files:
      - configs/config.yaml
