apiVersion: v1
kind: Service
metadata:
  name: gfingerd
  labels:
    app: gfingerd
spec:
  type: LoadBalancer
  selector:
    app: gfingerd
  ports:
    - name: finger
      protocol: TCP
      port: 79
      targetPort: finger
