homeassistant:
  name: Home
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  unit_system: metric
  currency: GBP
  time_zone: !env_var TZ
  external_url: https://home-assistant.homelab.adtennant.dev

default_config:

http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
