---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
configMapGenerator:
  - name: home-assistant
    files:
      - configuration.yaml
resources:
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - secret.enc.yaml
  - service.yaml
