---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant
  namespace: home-assistant
type: Opaque
data:
  LATITUDE: ENC[AES256_GCM,data:nt0+uGx0OGHd+ZhTEvBRY2qafV2n9xAE,iv:Bk/3sgCAHPCRPUpjTEC7geJuqoKLYtS5WHicKlcSfGk=,tag:MDxg1K6TKXwbmoNDZNiCtQ==,type:str]
  LONGITUDE: ENC[AES256_GCM,data:VVIaXPSr2/n6hhpbVLPhHXkUFaDTG17HtYHb8A==,iv:+18Hhw0hT4HSEnhfWCpkeCh/xai9LPD4WZ6dAV57Wo8=,tag:O9E2uumbn2EDElUtT9/HsA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-01-06T20:04:34Z"
  mac: ENC[AES256_GCM,data:pYVR7gHYnb81dYYvdnyZ2KYbu/bLikkgx1SDLS3MxIKbIUaou+9q22HkN5OTwQYCdTZqiEw/s2Idtq3AQMDDwvjzBlGH+WdAjbksmZc/7/jC+mcRshly2DzUTijBBDQzhU+vTVsNb83DNN+NGCNBk4Eg3qHHijLnO34EdC2/kjw=,iv:qiALyPWfzgSDTSyrw6XGb8GP/C5/MBYswqeRygmo9XI=,tag:KJxjHH4AHJBhVhYuZWOUaA==,type:str]
  pgp:
    - created_at: "2023-01-06T20:04:33Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0Zy+lejmH90ARAAtKbTnNMlCgRj0whnpyDvtOXVHjjbfkAg1nrCgofhRDfB
        /gHm5s4dA3YJLWeMKZ5f68Qla0etjipOh7wZYx40Gm2u9y2ZM2Bol/o+EW18AYB2
        pBPGjVlPYcsjSzIQoZ3suiPCpY9M8gnC3CjtmFDIz+K/YM6VO2bg+EgXZQD6yhSs
        8oJFJ9nntwTVi8LseBR8QZGlWZ+QiLLRul+dkcxPpBsnht8KOjxp/9uTncGCIQoU
        BPmeqS3ukcamGXcx0X3b4oRKouh6ng5nrM7Z6L+N2IyC4DO0/b8RuzyJdCrpfmVF
        hCNNnKuvj7CSlIi7ZO+1krqwBUpjuMFcKybLS46370IATCBEhq3zYqQDeGeL+d0j
        z/lGEgLlOCWSnjCfn4GeUsEC6s96YhHUpy1ZfpPvTPSWkdQ54nQO/qzFdO4NLqDx
        qiTGONTY3vc1zW5ob5OHUx4u5ZTbki4lteEc8W5+V5khtJp75jnZh5Sod9LxIFcD
        zg71YCXkwx7TPUcjQjlyGWJmOSlOhxWQi5dQI937Um2UanDH/dNV0mGVpLElErRP
        vKG2LTxYUCUBxLXAvdMxM54bUViVJ5NBUX2iVU5qLs/QHMGjIaQc4wvHmfFFBdtB
        12kUU0qwgGQrNElVyBCqNLWCFvsI8jBeF3szuhMhEtkzWL+1F+QM9UlOLTLrILfU
        ZgEJAhB+W7ifqtibj+emUIDGPjQFuC54SrRS/g80paTArignT8XsTy7evDee1P/o
        A7GYDfr/rYCO2V4u3sXK76Rub8aVD0Z55KcXRLWgJtq4c/7C8eOHMzjdcBNACsbq
        yggm+I5p2A==
        =O93z
        -----END PGP MESSAGE-----
      fp: 8858948C94A7459AB04B59D37BCE1C5040D2EEE4
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
