---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  # renovate
  - github.com/metallb/metallb//manifests?ref=v0.13.3
  - ipaddresspool.yaml
  - l2advertisement.yaml
  - secret.enc.yaml
