---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - deployment.yaml
  - ingress-internal.yaml
  - ingress-public.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
