---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
images:
  # https://github.com/kubernetes-sigs/external-dns/issues/1903
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.9.0
patchesStrategicMerge:
  - deployment.patch.yaml
resources:
  # renovate
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.8.0
  - namespace.yaml
  - secret.enc.yaml
