---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.30.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
  values:
    DNS1: 1.1.1.1
    DNS2: 1.0.0.1
    extraEnvVars:
      FTLCONF_dns_listeningMode: all
    ingress:
      enabled: true
      hosts:
        - pihole.homelab.local
    persistentVolumeClaim:
      enabled: true
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
        - 1.0.0.1
    serviceDhcp:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
    serviceDns:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/loadBalancerIPs: 192.168.50.250
      type: LoadBalancer
