apiVersion: v1
kind: Secret
metadata:
    name: octopus-api-key
data:
    OCTOPUS_API_KEY: ENC[AES256_GCM,data:DdUnOz7zWSHofYqyd1vYPuGCL68QjRQJUonGv6Nt2F5RZtIRcHJlkDkIe3Q=,iv:i0U8yNuf9geI60eCBPgM+VSypyzTKfd+ZNgS5Vro2BY=,tag:FRlw9StrJfVlqOyOsNYoTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-21T09:30:32Z"
    mac: ENC[AES256_GCM,data:4mrPMyj4wnScvsRQfGQhW2HCSYaNj4YkUHeM9/NMDyJDyTvpsBOGvtlZthbT9LcDrKShOTNJqegoeu+ePMRlJ0mbCBdyBtPzg0OS7OA38l829FWNPoNgrKrTYAZE45RZE9sAFObt3BTFxMLWAXDW4FYkU4FI9TdZLq+sioNfaCc=,iv:mPYVkKtM9vAdXYsz5b6On7zR5jl2yWDjlrIb1pL/tbc=,tag:bfvqidR+2CRaYR+G4wt51w==,type:str]
    pgp:
        - created_at: "2022-07-21T09:30:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Zy+lejmH90AQ//ZWbb8j69d2Y5xbsKTxSCADxFNiX3kLzVdJCmZkdeY5U2
            1Vn13+rJ9lmJiGLIF6EqR1Z5hpH2c/+BPPlrAImFs4Jzu3toW10FsDrX5XES0MBO
            W1dejIWGb8PDIlNbL2W5b41FLaPzXzXQOzk8wNML8VNsQIZ76Gw23K4aEi1yCv/l
            0YL863DXyrV2gWhAVS1akI0iy2d6SQHFwTMOv7lTzg4XDUdlMCsmn7dZzoGy0Xrk
            nUrUMv5+fA085iucD1fvqcQSZ0vGv9n7rXv4YxesuOebEq5Ck+4+EK/382us+VKJ
            ARlK6GDCVBTs8XqcWqd+jVhp3wIdz7xJRJ3MRisFwnSHAmuyivp4mivGKHkFDjTn
            5rtCQxaKisJBfAzqW3yYN5MjZefM7gQ5hyCzfqDHXkG/YQth93Kbo6g+n12dSiQH
            AmFDFUTFjoLhJbL1NON9v1rMj3p0che3C21ZhXxAbsu+Tz7tlA8/+ZpGFBT0GF57
            P7D1JKmwSb3BLK/syUaPHh8PLXytfhAI91QhWbr/vMV0QJQWqSuAKPsD//1onz6V
            qeJqwjv3T7TvHd+wZOVgaSA2TLThUQCWlEFkrkjRXfdJqF4hLRg7r46ilnU1soYD
            jCxHB7QptDwvOoYWFPkOwRD8YBU2OIEjlF/RHazAcRpeSxS7ZBcDTJx4UCXVPbXU
            aAEJAhDptvxzInh4UKkDLHorw4Yl0ordve88juBXzxG9cqCsyoVAWpAKB2C0pN89
            nV7AdkbrEq1l8DPmRiHgjchMhkA01AUDK4DC0y/zwASRncnSzsRCwqwQ+3pQQatT
            AHAFQBtcrK/G
            =hzi0
            -----END PGP MESSAGE-----
          fp: 8858948C94A7459AB04B59D37BCE1C5040D2EEE4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
