---
- hosts: all
  vars_prompt:
    - name: gpg_secret_key
      unsafe: yes
      private: yes

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: crontab

- import_playbook: k3s.orchestration.site

- hosts: server
  gather_facts: yes
  become: yes
  roles:
    - role: bootstrap
