apiVersion: v1
kind: Secret
metadata:
    name: github-credentials
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:AlRQCWzy9VKBz4L24+akr5qVpY0=,iv:U3ya70SkZhV6KjL3IH+Wqd7DgJgT4Cf2zno1tVNJjPA=,tag:+VLnM7qwLpbWyEGZ4vczZw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:DEHOh1UTqQm215qzSDxTnepJp5AN4mPdmaH6C6uDXb2NoPbFkxImCA==,iv:2errn6VEX6VYaXPSMXpXun2/GG0WjCmOZ4jxnSrhaow=,tag:Ja8UyzIgPiGnuMEORNIvEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T16:27:50Z"
    mac: ENC[AES256_GCM,data:MUUGzfWB4N3eKzjmN4CZJqhVlTXw88H+itBppS1vaHm2tGJLxvu1Jekkv0nBFh1TU5bk7pzdOThJV6n3M+o1LGd8ztpUXYCgct3sagJ3NoW3cjdbH1jtYMiTiB31bZYLqjhxufv+JUNei06m0b6i289CW68mO0znDug/uKJMRXA=,iv:1m3bCxYNh8dxOnH9HhffEO0vnm2b0QIJxsPVxx/aXIc=,tag:Chky/engSg/lvhzWpDBzkw==,type:str]
    pgp:
        - created_at: "2023-01-08T10:03:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Zy+lejmH90ARAAk/reL808X8aVAp7IRRaHVj3rvHIqT2s+QqnO3tVMfHNm
            UU5K3SgGOVuVqHH2sxvjSdu7VimMLSyhCiOCFToaq3+ztJ5rQ1ccCaWZJvyRe2wD
            6eLdnl6X1tvJNRjTTmXnsg+EtJTVRVRygWqlIV2iZX5rVJ0KMUGJ0fVWTF+HNmEM
            6B9IZJkgHf5wvjlxHFwA5THPk+PwChUd+NVexyoXHPjePYaZl/32ouH9DkaqYDMZ
            Rja8aPk8TIYh6e0p+nBJVSIXVUgVQORJ4uk1bpuk7B+AQK2defbRzTM4g2hcR8Ve
            84V63W0sF8EQTGOsVNfltS9SCWQKgC5t99diIW41906tslsgb+qmWiTQ6RHj5x/K
            gGH46j9c8yKapf7Lvv2eBKjsnpaqqqGTCpvozSgsh+mIxxNSXXA9SaGYY9kmj8Os
            2mVBv0sP2gZBqhLWHPWRc2oaiYuckPLl5BOU/VvfvRUp929sUsXiEHn624UO8csr
            rg3/xNCtwD4n54ifTjq2IhdmfWteiUsI5bsEm0hJWgEnw1JVWInTRMXy8oFwP6R+
            obc6ih0s6qINxSW4l20H1XeUIIZ8632YqeRqm56GjwUZFbn9eCbpTWphAgsIx2ms
            YGDiUn4HDq5cMzLB02eho6se9nSnNtq8z/Ym23MPCBGySReeRvDwGdqBl7fmnyrU
            aAEJAhCfsSnniOjxLtgTdSPyIJCPGXRI34xghnvKYWpQ0rNSDRBl+xQmZfU91Q7P
            T3j9lM6ZlumYO3PWk1Hqqt4Q7Hzvjva0YnO1lrfWaBZGgXATQ8ru3e30xHXyuil8
            QpI0vCuHprRo
            =Vmv+
            -----END PGP MESSAGE-----
          fp: 8858948C94A7459AB04B59D37BCE1C5040D2EEE4
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
