---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - home-assistant.yaml
  - longhorn.yaml
  - metallb.yaml
  - traefik.yaml
