---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: k8s/system-upgrade
    repoURL: https://github.com/adtennant/homelab.git
    targetRevision: argocd
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
