---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.70.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
