---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.3.6
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: podinfo.homelab.local
          paths:
            - path: /
              pathType: Prefix
