---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      # renovate: registryUrl=https://stefanprodan.github.io/podinfo
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
