---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - ingress-public.yaml
  - ingress-tailscale.yaml
  - namespace.yaml
