---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virgin-media-exporter
spec:
  selector:
    matchLabels:
      app: virgin-media-exporter
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: virgin-media-exporter
    spec:
      containers:
        - name: virgin-media-exporter
          image: ghcr.io/adtennant/virgin-media-exporter:master
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
