---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_API_TOKEN
    extraArgs:
      - --cloudflare-proxied
    policy: sync
    provider: cloudflare
