---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    provider: cloudflare
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: external-dns
              namespace: external-dns
            spec:
              template:
                spec:
                  containers:
                    - name: external-dns
                      envFrom:
                        - secretRef:
                            name: cloudflare-api-token
