---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt
      defaultIssuerKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io
